[package]
name = "jvm-rs"
version = "0.1.0"
authors = ["worldcreate <furatsuki_fiskm@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
